# Generated by Django 4.2 on 2025-10-08 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user", name="avatar", field=models.URLField(blank=True),
        ),
    ]
