# Generated by Django 4.2 on 2025-11-05 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="currency",
            field=models.CharField(
                blank=True,
                choices=[("won", "Korean Won"), ("usd", "Dollor")],
                max_length=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="language",
            field=models.CharField(
                blank=True,
                choices=[("kr", "Korean"), ("en", "English")],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user", name="avatar", field=models.URLField(blank=True),
        ),
    ]
