# Generated by Django 4.2 on 2025-11-05 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
        ("blogs", "0001_initial"),
        ("comments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlecomment",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="article_comments",
                to="articles.article",
            ),
        ),
        migrations.AlterField(
            model_name="postcomment",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_comments",
                to="blogs.post",
            ),
        ),
    ]
